version: '3'
services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: