// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :execresult
INSERT INTO entries (content)
VALUES (?)
`

func (q *Queries) CreateEntry(ctx context.Context, content string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEntry, content)
}

const getEntries = `-- name: GetEntries :many
SELECT id, content
FROM entries
ORDER BY created_at DESC
LIMIT ?
`

type GetEntriesRow struct {
	ID      int64
	Content string
}

func (q *Queries) GetEntries(ctx context.Context, limit int32) ([]GetEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesRow
	for rows.Next() {
		var i GetEntriesRow
		if err := rows.Scan(&i.ID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
